In [2]:
import numpy as np

In [3]:
#1
vector_10_to_49 = np.arange(10, 50)
print("1. Vector from 10 to 49:\n", vector_10_to_49)


1. Vector from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n2. 3x3 matrix from 0 to 8:\n", matrix_3x3)


2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 3. Create a 3x3 identity matrix.
identity_3x3 = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_3x3)


3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# 4. Create a 3x3x3 array with random values.
random_3x3x3 = np.random.rand(3, 3, 3)
print("\n4. 3x3x3 random array:\n", random_3x3x3)



4. 3x3x3 random array:
 [[[0.29619825 0.72131981 0.81148406]
  [0.34710135 0.50994738 0.18028098]
  [0.23689776 0.50384019 0.87131921]]

 [[0.21017321 0.51962671 0.79418577]
  [0.92271446 0.0912369  0.82324077]
  [0.72432268 0.2491671  0.0498    ]]

 [[0.72203706 0.11563814 0.56093578]
  [0.92004274 0.77627359 0.38547771]
  [0.7901064  0.59139138 0.72084245]]]


In [7]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_10x10 = np.random.rand(10, 10)
min_val = np.min(random_10x10)
max_val = np.max(random_10x10)
print("\n5. 10x10 random array min and max:\nMin:", min_val, "\nMax:", max_val)


5. 10x10 random array min and max:
Min: 0.003371075015898506 
Max: 0.9979445143933692


In [8]:
# 6. Create a random vector of size 30 and find the mean value.
random_vector_30 = np.random.rand(30)
mean_val = np.mean(random_vector_30)
print("\n6. Mean of random vector of size 30:", mean_val)


6. Mean of random vector of size 30: 0.48568539651192494


In [9]:
# 7. Normalize a 5x5 random matrix.
random_5x5 = np.random.rand(5, 5)
normalized_5x5 = (random_5x5 - np.min(random_5x5)) / (np.max(random_5x5) - np.min(random_5x5))
print("\n7. Normalized 5x5 matrix:\n", normalized_5x5)


7. Normalized 5x5 matrix:
 [[0.10739311 0.48800213 0.7096143  0.7737369  0.69414816]
 [0.47319177 0.08936945 0.6299188  0.42062943 0.97217085]
 [0.         0.17445611 0.87829401 0.04748291 0.98528535]
 [1.         0.95442302 0.34841047 0.4455176  0.69773578]
 [0.96685021 0.60759163 0.21341199 0.82596634 0.9690444 ]]


In [10]:
# 8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)
product_5x3_3x2 = np.dot(matrix_5x3, matrix_3x2)
print("\n8. Matrix product of 5x3 and 3x2 matrices:\n", product_5x3_3x2)



8. Matrix product of 5x3 and 3x2 matrices:
 [[0.39292463 1.21206353]
 [0.74987083 1.44140973]
 [0.87695919 1.13827332]
 [0.84156512 1.5641631 ]
 [0.82732004 1.84524273]]


In [11]:
# 9. Create two 3x3 matrices and compute their dot product.
matrix_A = np.random.rand(3, 3)
matrix_B = np.random.rand(3, 3)
dot_product_3x3 = np.dot(matrix_A, matrix_B)
print("\n9. Dot product of two 3x3 matrices:\n", dot_product_3x3)


9. Dot product of two 3x3 matrices:
 [[0.26960234 0.56974046 0.34290124]
 [0.81961594 1.32922019 1.13611494]
 [0.94073115 1.42446302 1.14980577]]


In [12]:
# 10. Given a 4x4 matrix, find its transpose.
matrix_4x4 = np.random.rand(4, 4)
transpose_4x4 = matrix_4x4.T
print("\n10. Transpose of 4x4 matrix:\n", transpose_4x4)


10. Transpose of 4x4 matrix:
 [[0.64726322 0.5813546  0.10951524 0.18659159]
 [0.99146766 0.90863608 0.76517147 0.13979804]
 [0.57665073 0.27466578 0.34427938 0.23120767]
 [0.3856844  0.30344885 0.31281345 0.56318508]]


In [13]:
# 11. Create a 3x3 matrix and calculate its determinant.
matrix_3x3_det = np.random.rand(3, 3)
determinant = np.linalg.det(matrix_3x3_det)
print("\n11. Determinant of 3x3 matrix:", determinant)


11. Determinant of 3x3 matrix: -0.15382857375835166


In [14]:
# 12. Create two matrices A (3x4) and B (4x3), and compute the matrix product A dot B.
matrix_A_3x4 = np.random.rand(3, 4)
matrix_B_4x3 = np.random.rand(4, 3)
product_A_B = np.dot(matrix_A_3x4, matrix_B_4x3)
print("\n12. Matrix product of A (3x4) and B (4x3):\n", product_A_B)


12. Matrix product of A (3x4) and B (4x3):
 [[1.36667136 1.47272172 0.98911714]
 [0.95410882 0.81586045 0.36931941]
 [1.64483537 1.51588844 0.71514472]]


In [15]:
# 13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.
matrix_3x3_mv = np.random.rand(3, 3)
vector_3 = np.random.rand(3, 1)
product_matrix_vector = np.dot(matrix_3x3_mv, vector_3)
print("\n13. Matrix-vector product:\n", product_matrix_vector)


13. Matrix-vector product:
 [[1.02739244]
 [0.18602595]
 [0.9465982 ]]


In [16]:
# 14. Solve the linear system Ax = b where A is a 3x3 matrix, and b is a 3x1 column vector.
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
x = np.linalg.solve(A, b)
print("\n14. Solution to Ax = b:\n", x)


14. Solution to Ax = b:
 [[-0.6630847 ]
 [-0.26538121]
 [ 2.29073651]]


In [17]:
# 15. Given a 5x5 matrix, find the row-wise and column-wise sums.
matrix_5x5_sums = np.random.rand(5, 5)
row_sums = np.sum(matrix_5x5_sums, axis=1)
col_sums = np.sum(matrix_5x5_sums, axis=0)
print("\n15. Row-wise sums:", row_sums, "\nColumn-wise sums:", col_sums)


15. Row-wise sums: [2.4282526  2.3941933  2.01880938 1.91638159 2.96130252] 
Column-wise sums: [3.4203107  2.37495051 1.82157582 2.31620485 1.78589751]
